# Generated by Django 4.2.16 on 2024-11-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='created_at',
            new_name='date',
        ),
    ]
